# ── FILE: docker-compose.yml
version: "3.9"
services:
api:
build: ./backend
env_file:
- ./backend/.env
ports:
- "8000:8000"
volumes:
- ./backend:/app
web:
build: ./frontend
ports:
- "3000:3000"
environment:
- NUXT_PUBLIC_API_URL=http://localhost:8000
volumes:
- ./frontend:/app
depends_on:
- api