# Generated by Django 4.2.24 on 2025-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('executive', 'Executive'), ('management', 'Management'), ('staff', 'Staff'), ('advisor', 'Advisor')], default='staff', max_length=20)),
                ('bio', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='team/')),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
