# Generated by Django 4.2.24 on 2025-10-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251024_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position_applied', models.CharField(choices=[('agriculture', 'Agriculture'), ('pharmacy', 'Pharmacy & Labs'), ('supply-chain', 'Supply Chain'), ('logistics', 'Logistics'), ('contracting', 'Contracting'), ('energy', 'Energy'), ('real-estate', 'Real Estate'), ('general', 'General/Any Department')], max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('cover_letter', models.TextField(max_length=1000)),
                ('cv_file', models.FileField(upload_to='applications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
